import Head from 'next/head';
import styles from './Layout.module.css';

const Layout = ({children, title = "KEVAREL"}) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.ico" />
            </Head>

            <header className={styles.header}>
                <h1 className={styles.title}>KEVAREL</h1>

            </header>

            <main className={styles.main}>
                {children}
            </main>

            <footer className={styles.footer}>
                KEVAREL | {(new Date().getFullYear())}
            </footer>
        </div>
    );
}

export default Layout;